etf_ticker = ['XLF', 'SPY', 'QQQ', 'XLU', 'XLE', 'IEFA', 'GDX', 'VCIT', 'SMH', 'XLI',
       'IAU', 'IEF', 'IVW', 'XLV', 'USHY', 'RSP', 'EWT', 'XLK', 'IJR', 'SPLG',
       'XLRE', 'GLD', 'DGRW', 'FPE', 'VCSH', 'VOO', 'XLY', 'SCHF', 'XHB',
       'CALF', 'SPTI', 'XLB', 'JPST', 'SPMB', 'IVV', 'VB', 'SJNK', 'SCHD',
       'DIA', 'PDBC', 'IWB', 'EMXC', 'VTV', 'QLD', 'SPEM', 'SPHY', 'VMBS',
       'COWZ', 'SCHR', 'SCHO', 'EWW', 'EWC', 'VGSH', 'IGSB', 'IWF', 'DGRO',
       'SPYV', 'SCHX', 'SPSM', 'ITOT', 'MBB', 'JCPB', 'IEI', 'SDVY', 'SPYG',
       'KIE', 'IJH', 'RDVY', 'FBND', 'ITB', 'PULS', 'BIZD', 'SCHG', 'SLYV',
       'VUG', 'VPL', 'DBC', 'IWR', 'IYE', 'VTIP', 'VGIT', 'EPI', 'XLG', 'IHI',
       'MOAT', 'BIV', 'FNDF', 'SOXX', 'IQLT', 'FDL', 'ANGL', 'SCHP', 'SPSB',
       'EELV', 'ICSH', 'VONG', 'FENY', 'VIG', 'VOE', 'FLOT', 'PAVE', 'SPHQ',
       'BBJP', 'KBA', 'SHYG', 'SPTS', 'MGK', 'TIPX', 'IDHQ', 'CIBR', 'ICOW',
       'NEAR', 'MUST', 'SPHB', 'FNDX', 'VDE', 'GSSC', 'FTSL', 'NOBL', 'IJS',
       'IDEV', 'FNDE', 'LMBS', 'HFXI', 'GTO', 'OMFL', 'PFFD', 'SPGP', 'DXJ',
       'IVE', 'GSY', 'HEFA', 'FGD', 'ULST', 'FALN', 'VRP', 'BAB', 'XCEM',
       'DGS', 'IYW', 'IUSV', 'JQUA', 'SLYG', 'IHDG', 'VO', 'VYMI', 'STIP',
       'MGV', 'LIT', 'VNLA', 'FNDA', 'SLQD', 'FLRN', 'HEWJ', 'PEY', 'DBEF',
       'PJUL', 'VFH', 'VGT', 'FLTR', 'VBR', 'SPTM', 'JMBS', 'DVY', 'VRIG',
       'PFXF', 'SDY', 'QQEW', 'HDEF', 'LGOV', 'HYDB', 'SPMO', 'FDVV', 'IUSG',
       'QQQE', 'EWL', 'FPEI', 'FTCS', 'JMST', 'FUTY', 'EMLP', 'PFFA', 'ESGU',
       'CWB', 'IFRA', 'RWJ', 'JHMM', 'ONEQ', 'XMHQ', 'VPU', 'RPV', 'IAGG',
       'PPA', 'JMUB', 'BBAX', 'BLOK', 'IWY', 'TDTT', 'EWM', 'SUSB', 'FTEC',
       'PRF', 'BSJP', 'PRFZ', 'ESGD', 'MDYV', 'DIVO', 'IXN', 'DLN', 'ECH',
       'FSMB', 'FLIN', 'AOA', 'EWD', 'RLY', 'DIVI', 'VV', 'URTH', 'OEF',
       'FHLC', 'FLBL', 'RWL', 'FV', 'IMCG', 'LVHI', 'VHT', 'TMFC', 'IJJ',
       'XAR', 'ICVT', 'ICF', 'VOOG', 'PID', 'JPEM', 'IOO', 'MMIT', 'DSTL',
       'ILCG', 'FSTA', 'FTXL', 'PCEF', 'FXO', 'RIGS', 'OMFS', 'EWJV', 'EWX',
       'CQQQ', 'TDTF', 'NUSC', 'GXG', 'SMMD', 'IYF', 'IEO', 'XMMO', 'IDOG',
       'SUSA', 'UITB', 'CDC', 'SECT', 'PICK', 'TUR', 'DNL', 'CEMB', 'SMLF',
       'FIVG', 'VIOO', 'FTXN', 'FCOM', 'FUMB', 'PSI', 'HTAB', 'DWAS', 'FDIS',
       'PHO', 'GOAU', 'IGEB', 'DSI', 'FXZ', 'EQAL', 'CHIQ', 'USTB', 'VOOV',
       'IYK', 'SYLD', 'MGC', 'IGBH', 'CEFS', 'HEDJ', 'FNX', 'XSD', 'VONE',
       'FXG', 'FTLS', 'OUSM', 'AIRR', 'EZA', 'AGZ', 'SMMU', 'VCR', 'VIOV',
       'CZA', 'MLPX', 'IVOO', 'FTSD', 'QGRO', 'PTNQ', 'JVAL', 'KORP', 'IYH',
       'BLCN', 'XSVM', 'NANR', 'TPYP', 'VAW', 'JPIB', 'NULG', 'CSB', 'DBEU',
       'RAVI', 'MMIN', 'NUMG', 'PTF', 'POCT', 'FYLD', 'IWL', 'REGL', 'EQWL',
       'JPSE', 'DIVB', 'FEMS', 'SDOG', 'NFTY', 'COM', 'KARS', 'IPAC', 'IHF',
       'DRSK', 'IGRO', 'CNYA', 'FCOR', 'HMOP', 'IAK', 'FIW', 'HEEM', 'XSMO',
       'DDWM', 'HYEM', 'DXJS', 'FVAL', 'QEFA', 'EZM', 'HAWX', 'FLJH', 'PTH',
       'FNDB', 'HYZD', 'IETC', 'PXF', 'QTUM', 'PXE', 'TRTY', 'FLQM', 'NUDM',
       'KBWP', 'YLD', 'EYLD', 'FDRR', 'RDIV', 'IUS', 'THD', 'FDHY', 'CMBS',
       'FLTW', 'RWK', 'WTV', 'ISCF', 'SKOR', 'VFVA', 'EMHY', 'BLES', 'FXL',
       'REZ', 'IAI', 'IGM', 'CDL', 'LSST', 'HEZU', 'BCD', 'RAAX', 'ONEY',
       'VFMF', 'EEMS', 'IPKW', 'RFV', 'EES', 'HSRT', 'DALI', 'IVOV', 'VFMO',
       'VPC']
