all_tickers = {
    'Industrials': ['CAT', 'UNP', 'GE', 'HON', 'BA', 'UPS', 'RTX', 'ETN', 'DE',
                    'LMT', 'ADP', 'ITW', 'WM', 'GD', 'CSX', 'NOC', 'PH', 'TT',
                    'CTAS', 'TDG', 'FDX', 'EMR', 'NSC', 'PCAR', 'RSG', 'CARR',
                    'CPRT', 'MMM', 'GWW', 'ODFL', 'PAYX', 'URI', 'WCN', 'FERG',
                    'FAST', 'LHX', 'AME', 'JCI', 'OTIS', 'VRSK', 'CMI', 'GPN',
                    'IR', 'ROK', 'EFX', 'PWR', 'XYL', 'SYM', 'DAL', 'WAB',
                    'VRT', 'HWM', 'BLDR', 'HEI-A', 'DOV', 'JBHT', 'AXON',
                    'VLTO', 'HUBB', 'LUV', 'BAH', 'EXPD', 'J', 'IEX', 'TXT',
                    'CSL', 'WSO', 'MAS', 'LII', 'AER', 'CNHI', 'NDSN', 'SAIA',
                    'POOL', 'GGG', 'XPO', 'UAL', 'SNA', 'SWK', 'TRU', 'LECO',
                    'OC', 'GFL', 'WMS', 'BLD', 'PNR', 'ACM', 'UHAL', 'AOS',
                    'ALLE', 'EME', 'HII', 'NVT', 'TTC', 'FBIN', 'RRX', 'ITT',
                    'WCC', 'TREX', 'WSC', 'AAL', 'CLH', 'KNX', 'TTEK', 'CNM',
                    'AGCO', 'CW', 'CHRW', 'RHI', 'FIX', 'APG', 'WWD', 'DCI',
                    'ARMK', 'MIDD', 'GNRC', 'BWXT', 'RBC', 'DLB', 'AYI', 'OSK',
                    'KBR', 'AIT', 'SITE', 'CR', 'WTS', 'MSA', 'FCN', 'LSTR',
                    'FLR', 'GXO', 'AAON', 'AZEK', 'ADT', 'HXL', 'CAR', 'TKR',
                    'TNET', 'MLI', 'MTZ', 'BECN', 'MSM', 'ZWS', 'ATKR', 'FLS',
                    'ESAB', 'FTAI', 'ATI', 'GTLS', 'DRS', 'R', 'CWST', 'MMS',
                    'KEX', 'LPX', 'VMI', 'SPXC', 'FSS', 'ALK', 'MOG-A', 'AL',
                    'AWI', 'FELE', 'GATX', 'SRCL', 'SNDR', 'HRI', 'CAAP',
                    'MATX', 'CPA', 'MDU', 'AEIS', 'JOBY', 'ACA', 'TEX', 'EXPO',
                    'WIRE', 'VRRM', 'BCO', 'ENS', 'KAI', 'NSP', 'CSWI', 'MAN',
                    'AVAV', 'GFF', 'GMS', 'SEB', 'CXT', 'DY', 'ARCB', 'SPR',
                    'GTES', 'NPO', 'ENOV', 'CBZ', 'JBT', 'HI', 'UNF', 'MGRC'],
    'Healthcare': ['LLY', 'UNH', 'JNJ', 'MRK', 'ABBV', 'TMO', 'ABT', 'DHR',
                   'AMGN', 'PFE', 'ISRG', 'SYK', 'ELV', 'MDT', 'VRTX', 'REGN',
                   'BMY', 'CVS', 'CI', 'BSX', 'GILD', 'ZTS', 'HCA', 'BDX',
                   'MCK', 'EW', 'IDXX', 'COR', 'DXCM', 'HUM', 'CNC', 'IQV',
                   'A', 'GEHC', 'BIIB', 'VEEV', 'MRNA', 'WST', 'RMD', 'ZBH',
                   'CAH', 'MTD', 'ICLR', 'ALGN', 'MOH', 'STE', 'ILMN', 'ALNY',
                   'BAX', 'WBA', 'WAT', 'LH', 'COO', 'RPRX', 'HOLX', 'BMRN',
                   'DGX', 'VTRS', 'PODD', 'NBIX', 'INCY', 'RVTY', 'KRTX',
                   'SRPT', 'TFX', 'EXAS', 'RGEN', 'CRL', 'UHS', 'TECH', 'PEN',
                   'CTLT', 'DVA', 'MEDP', 'UTHR', 'QGEN', 'BRKR', 'HSIC',
                   'BIO', 'ATR', 'THC', 'CHE', 'IMGN', 'ROIV', 'STVN', 'SWAV',
                   'NTRA', 'APLS', 'PCVX', 'ELAN', 'CYTK', 'CERE', 'JAZZ',
                   'ACHC', 'IONS', 'EHC', 'GMED', 'MASI', 'XRAY', 'ITCI',
                   'HQY', 'ENSG', 'EXEL', 'BBIO', 'TXG', 'OPCH', 'INSP',
                   'CRSP', 'DOCS', 'NUVL', 'IMVT', 'RVMD', 'GKOS', 'HALO',
                   'BPMC', 'MMSI', 'ALKS', 'SHC', 'AXSM', 'QDEL', 'RCM',
                   'ACAD', 'PRGO', 'SGRY', 'OGN', 'ALVO', 'INSM', 'ARWR',
                   'OSCR', 'FOLD', 'BHVN', 'PGNY', 'LNTH', 'RARE', 'MLTX',
                   'XENE', 'HAE', 'NVST', 'MDGL', 'RYZB', 'IRTC', 'AZTA',
                   'NEOG', 'EVH', 'ITGR', 'AXNX', 'TDOC', 'PBH', 'NARI', 'SEM',
                   'SWTX', 'ACLX', 'IART', 'IDYA', 'KRYS', 'VKTX', 'AMED',
                   'RYTM', 'CBAY', 'TMDX', 'AMN', 'FTRE', 'NMRA', 'AGL',
                   'CERT', 'ARVN', 'GH', 'LIVN', 'CNMD', 'AMPH', 'RCKT',
                   'PDCO', 'GDRX', 'CGON', 'CRNX', 'RDNT', 'PINC', 'NTLA',
                   'PRCT', 'LFST', 'DNLI', 'PRVA', 'ICUI', 'IRWD', 'CORT',
                   'BEAM', 'MRUS', 'IOVA', 'VERA', 'ATEC', 'ARDX', 'VCEL',
                   'TGTX', 'KYMR', 'TWST', 'RXRX', 'INMD', 'CLDX', 'MYGN',
                   'SDGR', 'MORF', 'HRMY', 'BTSG', 'PTCT', 'DYN', 'SNDX',
                   'VCYT', 'NEO', 'KROS', 'APGE', 'EWTX', 'RXST', 'PACB',
                   'INBX', 'AMAM', 'AMRX', 'AMEH', 'ALPN', 'NAMS', 'DVAX',
                   'IRON', 'NVCR', 'WRBY', 'OMI', 'CPRX', 'TARO', 'ATRC',
                   'PHR', 'PTGX', 'ADUS', 'SUPN', 'PRTA', 'TNDM', 'KURA',
                   'SLNO', 'PHVS', 'ABCL', 'STAA', 'USPH', 'KNSA', 'RCUS',
                   'SAGE', 'NHC', 'EYPT', 'AGIO', 'MRVI', 'LMAT', 'DAWN',
                   'PCRX', 'UFPT', 'LGND', 'MIRM', 'SANA', 'ALHC', 'DCPH',
                   'TNGX', 'VIR', 'OMCL', 'FDMT', 'BCRX', 'FNA', 'AUPH',
                   'ADMA', 'XNCR', 'IMTX', 'MDXG', 'RLAY', 'ANIP', 'LQDA',
                   'CTKB', 'SRRK', 'VRDN', 'AKRO', 'COLL', 'AMLX', 'DH',
                   'MGNX', 'CABA', 'RNA', 'ARCT', 'SAVA', 'ACCD', 'IMNM',
                   'ESTA', 'BKD', 'TARS', 'GYRE', 'PLRX', 'AHCO', 'INVA',
                   'VERV', 'AGTI', 'TYRA', 'TMCI', 'NRC', 'TRML', 'EMBC',
                   'MDRX', 'CRGX', 'QTRX'],
    'Technology': ['MSFT', 'AAPL', 'NVDA', 'AVGO', 'ORCL', 'ADBE', 'CRM',
                   'AMD', 'ACN', 'CSCO', 'INTU', 'INTC', 'IBM', 'QCOM', 'NOW',
                   'AMAT', 'TXN', 'UBER', 'LRCX', 'PANW', 'SHOP', 'ADI', 'MU',
                   'KLAC', 'ANET', 'SNPS', 'FI', 'CDNS', 'WDAY', 'CRWD',
                   'SNOW', 'APH', 'DELL', 'NXPI', 'MRVL', 'ROP', 'ADSK',
                   'TEAM', 'MSI', 'FTNT', 'PLTR', 'MCHP', 'TEL', 'DDOG',
                   'SMCI', 'SQ', 'CTSH', 'ZS', 'FIS', 'IT', 'NET', 'MDB',
                   'MPWR', 'TTD', 'ON', 'FICO', 'CDW', 'HUBS', 'GFS', 'ANSS',
                   'FTV', 'KEYS', 'HPQ', 'GLW', 'SPLK', 'GRMN', 'BR', 'PTC',
                   'TDY', 'VRSN', 'HPE', 'ZM', 'FLT', 'AKAM', 'CHKP', 'IOT',
                   'ENTG', 'STX', 'TYL', 'NTAP', 'WDC', 'JBL', 'SWKS', 'ENPH',
                   'EPAM', 'FSLR', 'GDDY', 'DT', 'TER', 'BSY', 'LDOS', 'APP',
                   'MANH', 'SSNC', 'PATH', 'OKTA', 'PSTG', 'NTNX', 'GEN',
                   'AFRM', 'TRMB', 'ZBRA', 'ESTC', 'U', 'JKHY', 'GTLB', 'AZPN',
                   'JNPR', 'CYBR', 'ZI', 'MNDY', 'FLEX', 'DBX', 'FFIV', 'PAYC',
                   'QRVO', 'PCOR', 'MSTR', 'DOX', 'DOCU', 'TOST', 'GLOB',
                   'CFLT', 'GWRE', 'LSCC', 'COHR', 'PCTY', 'WEX', 'INFA',
                   'SNX', 'S', 'ONTO', 'OLED', 'NXT', 'APPF', 'CIEN', 'DUOL',
                   'CACI', 'MKSI', 'KVYO', 'SPSC', 'AMKR', 'WIX', 'ALTR', 'FN',
                   'PSN', 'UI', 'DV', 'BILL', 'SAIC', 'CCCS', 'G', 'SMAR',
                   'FRSH', 'FOUR', 'CGNX', 'QLYS', 'RMBS', 'NSIT', 'CLVT',
                   'LFUS', 'TENB', 'ALGM', 'ARW', 'MTSI', 'NOVT', 'BRZE',
                   'FIVN', 'STNE', 'VRNS', 'VNT', 'CNXC', 'CWAN', 'WK', 'GBTG',
                   'ALIT', 'LYFT', 'EXLS', 'PWSC', 'KD', 'CRUS', 'ST', 'DLO',
                   'HCP', 'IPGP', 'EEFT', 'TDC', 'POWI', 'NVMI', 'SLAB',
                   'ASGN', 'SQSP', 'BLKB', 'SEDG', 'ASAN', 'SYNA', 'BMI',
                   'PAGS', 'PEGA', 'CVLT', 'FROG', 'ACLS', 'VERX', 'AVT',
                   'DXC', 'BOX', 'BL', 'RPD', 'SPT', 'SATS', 'CAMT', 'WOLF',
                   'CRDO', 'NCNO', 'INST', 'CXM', 'PYCR', 'ITRI', 'BDC', 'AYX',
                   'RUN', 'AI', 'SANM', 'DOCN', 'RELY', 'LITE', 'FORM', 'ACIW',
                   'ALRM', 'DIOD', 'FSLY', 'RNG', 'SRAD', 'VSH', 'MQ', 'YOU',
                   'PI', 'INTA', 'ENV', 'SITM', 'KLIC', 'SHLS', 'FLYW', 'EVTC',
                   'PLXS', 'IDCC', 'ODD', 'RAMP', 'JAMF', 'QTWO', 'ESE',
                   'PRFT', 'PRGS', 'BMBL', 'VSAT', 'ALKT', 'AVDX', 'NABL',
                   'AGYS', 'APPN', 'OSIS', 'PD', 'ARRY', 'IONQ', 'CALX', 'XRX',
                   'SONO', 'AMBA', 'ROG', 'RUM', 'VYX', 'SWI', 'ZETA', 'PLAB',
                   'PLUS', 'PAY', 'VIAV', 'VRNT', 'UCTT', 'VICR', 'VECO',
                   'EVCM', 'CLBT', 'PAYO', 'UPBD', 'CNXN', 'SEMR', 'PRO',
                   'AMPL', 'NATL', 'TTMI', 'COHU', 'EXTR', 'CSGS', 'SPNS',
                   'MXL', 'HLIT', 'AVPT', 'VZIO', 'NTCT', 'MLNK', 'CSIQ', 'KN',
                   'GRND', 'VTEX', 'NOVA', 'CTS', 'ADEA', 'CRSR', 'SMTC',
                   'PAR', 'BASE', 'PDFS', 'STER', 'ICHR', 'ZUO', 'DBD', 'INFN',
                   'INDI', 'NVTS', 'GCT', 'SGH', 'EVBG', 'CRCT', 'ACMR',
                   'TASK', 'MODN', 'BHE', 'DGII', 'GDYN', 'SCSC', 'ATEN',
                   'OLO', 'WKME', 'WEAV', 'BELFB', 'SSYS', 'EB', 'BTDR',
                   'TTEC', 'PSFE', 'WALD', 'DMRC', 'RDWR', 'PUBM', 'RPAY',
                   'AAOI', 'MEI', 'YEXT', 'ENFN', 'IMXI', 'KARO', 'CRNC',
                   'AOSL', 'BIGC', 'LASR', 'SNPO', 'HCKT', 'IIIV', 'SCWX',
                   'MITK', 'DSP', 'SMWB', 'CGNT', 'ITRN', 'ADTN', 'CEVA', 'ML',
                   'MLAB', 'AEHR', 'LAW', 'UIS', 'SKYT', 'XPER', 'ALNT',
                   'CTLP', 'DJCO', 'RDZN', 'CLFD', 'FARO', 'DOMO', 'VPG',
                   'OSPN', 'AVNW', 'NVEC', 'LYTS', 'NTGR', 'CCSI', 'AMSWA',
                   'BAND', 'GILT', 'DAKT', 'BLZE', 'ONTF', 'INOD', 'IBEX',
                   'MAXN', 'CLMB', 'LUNA', 'SSTI'],
    'Utilities': ['AES', 'LNT', 'AEE', 'AEP', 'AWK', 'ATO', 'CNP', 'CMS', 'ED',
                  'CEG', 'D', 'DTE', 'DUK', 'EIX', 'ETR', 'EVRG', 'ES', 'EXC',
                  'FE', 'NEE', 'NI', 'NRG', 'PCG', 'PNW', 'PPL', 'PEG', 'SRE',
                  'SO', 'WEC', 'XEL'],
    'Financial Services': ['BRK-B', 'JPM', 'V', 'MA', 'BAC', 'WFC', 'BX',
                           'AXP', 'MS', 'SPGI', 'RY', 'C', 'GS', 'BLK', 'SCHW',
                           'TD', 'PGR', 'CB', 'MMC', 'KKR', 'ICE', 'MCO',
                           'CME', 'PYPL', 'USB', 'APO', 'AON', 'PNC', 'AJG',
                           'COF', 'MET', 'TRV', 'AIG', 'TFC', 'NU', 'MSCI',
                           'AFL', 'ARES', 'BK', 'ALL', 'IBKR', 'AMP', 'PRU',
                           'COIN', 'NDAQ', 'ACGL', 'WTW', 'DFS', 'HIG', 'OWL',
                           'TW', 'RJF', 'TROW', 'BRO', 'RKT', 'FITB', 'MTB',
                           'STT', 'UWMC', 'FCNCA', 'WRB', 'CBOE', 'MKL', 'PFG',
                           'ERIE', 'LPLA', 'FDS', 'HBAN', 'CINF', 'RF', 'NTRS',
                           'CG', 'L', 'TPG', 'SYF', 'EG', 'ALLY', 'CRBG',
                           'CFG', 'BEN', 'FNF', 'XP', 'KEY', 'CNA', 'BAP',
                           'MORN', 'RNR', 'GL', 'ARCC', 'RYAN', 'EQH', 'RGA',
                           'AFG', 'HOOD', 'EWBC', 'KNSL', 'UNM', 'AIZ', 'HLI',
                           'SEIC', 'JEF', 'PRI', 'MKTX', 'WBS', 'SOFI', 'ORI',
                           'SF', 'FHN', 'VOYA', 'IVZ', 'CACC', 'CMA', 'WAL',
                           'EVR', 'CBSH', 'CFR', 'RLI', 'HLNE', 'PNFP', 'SSB',
                           'BPOP', 'FAF', 'SIGI', 'ZION', 'PB', 'FG', 'WTFC',
                           'OBDC', 'FSK', 'ESNT', 'BOKF', 'OMF', 'FCFS',
                           'MARA', 'SNV', 'AMG', 'PDI', 'BXSL', 'MTG', 'AXS',
                           'JHG', 'FRHC', 'CADE', 'DNB', 'OZK', 'HOMB', 'UBSI',
                           'ONB', 'THG', 'FNB', 'AGO', 'COOP', 'PFSI', 'FFIN',
                           'ESGR', 'AEL', 'WU', 'LNC', 'ACT', 'SLM', 'VLY',
                           'RDN', 'CRVL', 'WTM', 'GBCI', 'JXN', 'STEP', 'UMBF',
                           'COLB', 'KMPR', 'PJT', 'BGC', 'PSLV', 'MAIN',
                           'TFSL', 'HWC', 'AB', 'MC', 'CNS', 'SFBS', 'LAZ',
                           'BHF', 'NNI', 'IBOC', 'ABCB', 'NEA', 'UCBI', 'GSHD',
                           'BUR', 'WD', 'DNP', 'ASB', 'FHI', 'RIOT', 'CNO',
                           'APAM', 'BANF', 'AX', 'CATY', 'UPST', 'FBP', 'PIPR',
                           'HGTY', 'TCBI', 'GNW', 'CLSK', 'FHB', 'FIBK',
                           'VIRT', 'NAD', 'GBDC', 'HTGC', 'WSFS', 'FULT',
                           'NVG', 'CSQ', 'AUB', 'EBC', 'BOH', 'NMIH', 'EXG',
                           'VCTR', 'INTR', 'CVBF', 'CBU', 'AMK', 'PPBI',
                           'TBBK', 'ADX', 'NZF', 'SFNC', 'INDB', 'MCY', 'BANC',
                           'PSEC', 'PAX', 'PRK', 'FFBC', 'UTF', 'SBCF', 'SNEX',
                           'TOWN', 'SPNT', 'ETY', 'HTH', 'FRME', 'PTY', 'GDV',
                           'BKU', 'UTG', 'DFIN', 'TSLX', 'IBTX', 'TFIN',
                           'BIGZ', 'NAVI', 'NUV', 'WAFD', 'CLBK', 'MSDL',
                           'GOF', 'USA', 'RNST', 'OBDE', 'NWLI', 'MBIN',
                           'DWAC', 'BFH', 'ECAT', 'BMEZ', 'LOB', 'FBK', 'OFG',
                           'AGM-A', 'WSBC', 'BCAT', 'VRTS', 'LKFN', 'TRMK',
                           'EVT', 'STC', 'GCMG', 'CLM', 'GSBD', 'CUBI', 'RVT',
                           'ENVA', 'NBTB', 'NAC', 'RQI', 'GAB', 'BRP', 'OCSL',
                           'FIHL', 'BANR', 'HMN', 'NWBI', 'CHCO', 'PLMR',
                           'ETV', 'BTT', 'EFSC', 'BDJ', 'FBNC', 'KYN', 'PDO',
                           'HTLF', 'BSTZ', 'NTB', 'STEW', 'HYT', 'SYBT',
                           'BXMX', 'FCF', 'ETG', 'CASH', 'DSL', 'NBHC', 'STEL',
                           'HOPE', 'BUSE', 'NMFC', 'TRUP', 'BST', 'SAFT',
                           'SRCE', 'SKWD', 'STBA', 'WABC', 'ECPG', 'PFS',
                           'OXLC', 'NFJ', 'LMND', 'QQQX', 'TCBK', 'EVV',
                           'BRDG', 'NIC', 'JFR', 'NMZ', 'PWP', 'VBTX', 'CET',
                           'EIG', 'PX', 'WT', 'GAM', 'MUC', 'FPF', 'EOS',
                           'PTA', 'BBN', 'SASR', 'BTZ', 'CSWC', 'PEBO', 'SCRM',
                           'BHLB', 'CVII', 'NCDL', 'BCSF', 'QCRH', 'RBCAA',
                           'RNP', 'GABC', 'OCFC', 'AMSF', 'LC', 'PFBC', 'NRK',
                           'PRAA', 'BBDC', 'OBK', 'SBSI', 'HCI', 'BY', 'CHY',
                           'BRKL', 'GHLD', 'LPRO', 'MFIC', 'AWF', 'BSIG',
                           'BFC', 'MQY', 'ETW', 'BLX', 'CII', 'AOD', 'MUI',
                           'HQH', 'HG', 'CHI', 'CFFN', 'SLRC', 'LBAI', 'CNOB',
                           'THQ', 'CRF'],
    'Basic Materials': ['LIN', 'SHW', 'SCCO', 'ECL', 'FCX', 'CRH', 'APD',
                        'NUE', 'DOW', 'NEM', 'CTVA', 'PPG', 'MLM', 'VMC',
                        'LYB', 'DD', 'IFF', 'STLD', 'WLK', 'RS', 'CE', 'AVTR',
                        'CF', 'RPM', 'ALB', 'X', 'CLF', 'MOS', 'EMN', 'EXP',
                        'SSD', 'UFPI', 'RGLD', 'AU', 'AXTA', 'SUM', 'FMC',
                        'CMC', 'OLN', 'NEU', 'BCC', 'ESI', 'AMR', 'AA', 'BCPC',
                        'ASH', 'CC', 'CBT', 'HUN', 'FUL', 'KNF', 'WDFC', 'KWR',
                        'AVNT', 'SMG', 'ARCH', 'HCC', 'MP', 'IOSP', 'CSTM',
                        'MTRN', 'SXT', 'TGLS', 'MTX', 'TROX', 'SCL', 'SLVM',
                        'NGVT', 'GPRE', 'WS', 'USLM', 'OEC', 'HWKN', 'ECVT',
                        'KOP', 'KALU', 'KRO', 'IE', 'GSM', 'CENX', 'LVRO',
                        'SXC', 'TMST', 'NEXA', 'WTTR', 'CMP', 'BIOX', 'SA',
                        'METC', 'PRM', 'WLKP', 'ZEUS', 'REX', 'UAN', 'ASIX',
                        'RDUS', 'HDSN', 'MATV', 'MTAL', 'LWLG', 'LXU', 'CLW',
                        'MERC', 'ODC', 'GATO', 'LZM', 'VHI', 'MUX', 'AVD',
                        'PLL', 'FF', 'IPI', 'MSB', 'SMID', 'CAPT', 'ATLX',
                        'TSE', 'CMCL', 'USAP', 'CTGO', 'CMT', 'NTIC', 'FRD',
                        'ACNT', 'IDR', 'USGO', 'JCTCF'],
    'Consumer Cyclical': ['AMZN', 'TSLA', 'HD', 'MCD', 'NKE', 'BKNG', 'LOW',
                          'TJX', 'SBUX', 'ABNB', 'MELI', 'STLA', 'MAR', 'CMG',
                          'ORLY', 'LULU', 'F', 'ROST', 'HLT', 'DHI', 'AZO',
                          'GM', 'LEN', 'LVS', 'YUM', 'RCL', 'CPNG', 'TSCO',
                          'ULTA', 'NVR', 'APTV', 'MBLY', 'EBAY', 'PHM', 'DECK',
                          'ROL', 'DKNG', 'GPC', 'DRI', 'CCL', 'BALL', 'EXPE',
                          'AVY', 'YUMC', 'BBY', 'RIVN', 'MGM', 'PKG', 'DPZ',
                          'WSM', 'H', 'DKS', 'AMCR', 'LKQ', 'BURL', 'VFS',
                          'IP', 'WYNN', 'KMX', 'FND', 'RL', 'WRK', 'CASY',
                          'TOL', 'FIVE', 'PAG', 'BBWI', 'SCI', 'TPR', 'CZR',
                          'CVNA', 'ONON', 'ETSY', 'CHDN', 'ALV', 'SKX', 'CCK',
                          'TXRH', 'BIRK', 'TPX', 'WING', 'MTN', 'LAD', 'GNTX',
                          'MUSA', 'LNW', 'LEA', 'PVH', 'GPK', 'CHWY', 'BWA',
                          'CART', 'GPS', 'AS', 'SN', 'LEVI', 'HAS', 'MHK',
                          'NCLH', 'GLBE', 'BERY', 'MAT', 'DDS', 'WH', 'HRB',
                          'BYD', 'CROX', 'AN', 'MMYT', 'THO', 'W', 'PLNT',
                          'CHH', 'CAVA', 'WHR', 'REYN', 'VFC', 'BC', 'IBP',
                          'BFAM', 'TMHC', 'MTH', 'SON', 'ANF', 'ALSN', 'CPRI',
                          'IGT', 'M', 'SEE', 'PII', 'HOG', 'ASO', 'BROS',
                          'COLM', 'SLGN', 'RH', 'SKY', 'MDC', 'KBH', 'HGV',
                          'SIG', 'GME', 'ABG', 'AEO', 'GOLF', 'WEN', 'YETI',
                          'URBN', 'MOD', 'GT', 'GPI', 'AAP', 'RUSHA', 'QS',
                          'PENN', 'UAA', 'KTB', 'RRR', 'TPH', 'MHO', 'SHAK',
                          'VC', 'SVV', 'SEAS', 'ZGN', 'SHOO', 'ADNT', 'JWN',
                          'DFH', 'CVCO', 'VAC', 'TRIP', 'CRI', 'KSS', 'TNL',
                          'GEF', 'LCII', 'LGIH', 'MCW', 'AIN', 'CCS', 'FOXF',
                          'FL', 'LEG', 'CARG', 'BOOT', 'LTH', 'FTDR', 'DORM',
                          'PTVE', 'MODG', 'ARCO', 'PATK', 'GRBK', 'OI', 'PZZA',
                          'BLMN', 'ACVA', 'VSCO', 'BOWL', 'DRVN', 'LVWR',
                          'FUN', 'SIX', 'GTX', 'ODP', 'BKE', 'MLKN', 'WGO',
                          'DAN', 'EAT', 'SAH', 'NWTN', 'MBC', 'CAKE', 'MSGE',
                          'CBRL', 'VSTO', 'ARHS', 'LZB', 'THRM', 'EYE', 'KAR',
                          'OXM', 'JACK', 'AMWD', 'CNNE', 'XPEL', 'OSW', 'GIII',
                          'LESL', 'PHIN', 'FWRG', 'SBH', 'SG', 'MCRI', 'WINA',
                          'RSI', 'GES', 'CARS', 'CAL', 'RVLV', 'PLYA', 'KRUS',
                          'CWH', 'GDEN', 'BYON', 'SHCO', 'FIGS', 'TRS', 'HOV',
                          'MBUU', 'BLBD', 'MNRO', 'AXL', 'ARKO', 'NGMS',
                          'EVRI', 'BZH', 'SMP', 'ACEL', 'HIBB', 'BJRI', 'PTLO',
                          'ETD', 'SCVL', 'HZO', 'MYE', 'DIN', 'WWW', 'SDA',
                          'MOV', 'LEGH', 'CHUY', 'FLWS', 'MED', 'PLOW', 'HVT',
                          'DESP', 'DENN', 'DBI', 'KRT', 'RICK', 'XPOF', 'BALY',
                          'TAST', 'SRI', 'LIND', 'MLR', 'BWMX', 'BH', 'LQDT',
                          'JOUT', 'JL', 'ONEW', 'CRMT', 'FNKO', 'LOVE', 'IRBT',
                          'MPX', 'MCFT', 'CSV', 'PBPB', 'ZUMZ', 'UHG', 'AGS',
                          'CYD', 'GAMB', 'GCO', 'JAKK', 'BBW', 'WEYS', 'CPS',
                          'LOCO', 'TTSH', 'LE', 'NATH', 'JILL', 'HOFT', 'HBB',
                          'GENK', 'CTRN', 'KFS', 'INSE', 'VRA', 'ESCA', 'CLAR',
                          'RMBL', 'SGC', 'SNBR', 'TLYS', 'CVGI', 'RCKY',
                          'LCUT', 'FLL', 'FLXS', 'MPAA', 'RRGB', 'PLCE',
                          'VIRC', 'FAT', 'CATO', 'BSET', 'LAKE', 'BGFV',
                          'AOUT', 'CPHC', 'STRT', 'UFI', 'AKA', 'KEQU', 'LIVE',
                          'NHTC', 'CULP', 'REE', 'CRWS', 'DLA', 'ARKR', 'INTG',
                          'BDL', 'MULN', 'CREV', 'RGS', 'YOSH', 'PMNT'],
    'Real Estate': ['EXPI', 'PEB', 'GNL', 'AKR', 'IVT', 'AAT', 'ROIC', 'JBGS',
                    'FOR', 'NXRT', 'RC', 'VRE', 'ARI', 'MMI', 'SAFE', 'XHR',
                    'GTY', 'NTST', 'CMTG', 'KW', 'LADR', 'SVC', 'TWO', 'LTC',
                    'ELME', 'ALEX', 'BFS', 'PMT', 'ALX', 'DEA', 'HPP', 'MFA',
                    'AIV', 'AHH', 'PLYM', 'FBRT', 'UMH', 'EFC', 'ARR', 'RDFN',
                    'CSR', 'BRSP', 'RWT', 'HOUS', 'PDM', 'CBL', 'CHCT', 'INN',
                    'DX', 'NYMT', 'KREF', 'WSR', 'GMRE', 'FRPH', 'FPI', 'PKST',
                    'UHT', 'SRG', 'CLDT', 'GOOD', 'LAND', 'ACRE', 'LSEA',
                    'OLP', 'RMR', 'ORC', 'IVR', 'STRW', 'TRTX', 'MLP', 'PSTL',
                    'CTO', 'ARL', 'NLOP', 'TCI', 'NREF', 'BRT', 'RMAX', 'REFI',
                    'GPMT', 'NXDT', 'AOMR', 'OPAD', 'PINE', 'AFCG', 'CLPR',
                    'SDHC', 'OZ', 'STRS', 'SEVN', 'MITT', 'STHO', 'MDV', 'AXR',
                    'EARN', 'ACR', 'BHM', 'NYC', 'GYRO', 'MDRR'],
    'Communication Services': ['GOOG', 'META', 'NFLX', 'DIS', 'TMUS', 'CMCSA',
                               'VZ', 'T', 'DASH', 'SPOT', 'CHTR', 'EA', 'RBLX',
                               'TTWO', 'PINS', 'WBD', 'LYV', 'WMG', 'SNAP',
                               'OMC', 'FWONA', 'NWSA', 'FOXA', 'ROKU', 'TWLO',
                               'ZG', 'IPG', 'LSXMA', 'MTCH', 'LBRDA', 'PARA',
                               'LBTYA', 'EDR', 'NYT', 'TKO', 'FYBR', 'NXST',
                               'MSGS', 'IAC', 'IRDM', 'CCOI', 'USM', 'MANU',
                               'LLYVA', 'YELP', 'ZD', 'TGNA', 'TIGO', 'CABO',
                               'PLTK', 'BATRA', 'IAS', 'PLAY', 'CMPR', 'LGF-B',
                               'TDS', 'ROVR', 'WLY', 'CNK', 'STGW', 'SSTK',
                               'GENI', 'SPHR', 'LILA', 'MGNI', 'GOGO', 'SEAT',
                               'NRDS', 'SCHL', 'FVRR', 'SHEN', 'TTGT', 'MAX',
                               'SBGI', 'IDT', 'DLX', 'QNST', 'GTN-A', 'IMAX',
                               'THRY', 'AMCX', 'GRPN', 'ATEX', 'ATNI', 'EVER',
                               'SSP', 'BOC', 'MCS', 'RSVR', 'EEX', 'OOMA',
                               'CDLX', 'DRCT', 'TSQ', 'CXDO', 'RDCM', 'SGA',
                               'SKLZ', 'TZOO', 'HAO'],
    'Consumer Defensive': ['WMT', 'PG', 'COST', 'KO', 'PEP', 'PM', 'MDLZ',
                           'MO', 'CL', 'TGT', 'MNST', 'EL', 'STZ', 'KHC',
                           'KDP', 'KMB', 'HSY', 'SYY', 'KVUE', 'GIS', 'KR',
                           'DLTR', 'DG', 'ADM', 'BF-B', 'CHD', 'CLX', 'TSN',
                           'K', 'MKC', 'HRL', 'LW', 'SJM', 'CELH', 'CAG',
                           'TAP', 'BG', 'CPB', 'ACI', 'USFD', 'PFGC', 'COTY',
                           'ELF', 'BJ', 'COKE', 'BRBR', 'INGR', 'DAR', 'PPC',
                           'POST', 'SFM', 'LANC', 'IPAR', 'OLLI', 'FLO',
                           'FIZZ', 'SAM', 'FRPT', 'LOPE', 'SMPL', 'GHC',
                           'NOMD', 'JJSF', 'NWL', 'HELE', 'COUR', 'CALM',
                           'LRN', 'SPB', 'GO', 'PSMT', 'STRA', 'THS', 'DNUT',
                           'SOVO', 'UDMY', 'HIMS', 'LAUR', 'CENT', 'EPC',
                           'ATGE', 'AFYA', 'MGPI', 'ANDE', 'WMK', 'VGR', 'UTZ',
                           'IMKTA', 'CHEF', 'TR', 'UVV', 'HLF', 'PRDO', 'JBSS',
                           'COCO', 'FDP', 'KLG', 'AGRO', 'DOLE', 'NAPA'],
    'Energy': ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'PSX', 'MPC', 'EPD', 'PXD',
               'OXY', 'VLO', 'ET', 'HES', 'WMB', 'OKE', 'MPLX', 'LNG', 'KMI',
               'HAL', 'BKR', 'FANG', 'DVN', 'CQP', 'TRGP', 'CTRA', 'EQT',
               'MRO', 'DINO', 'OVV', 'TPL', 'PAA', 'WES', 'PR', 'CHK', 'APA',
               'FTI', 'HESM', 'IEP', 'SWN', 'WFRD', 'NOV', 'RRC', 'PBF',
               'MTDR', 'CHRD', 'AR', 'NE', 'CIVI', 'MUR', 'AM', 'VNOM', 'CHX',
               'ENLC', 'VVV', 'SUN', 'DTM', 'FRO', 'VAL', 'ETRN', 'NFG',
               'PTEN', 'SM', 'MGY', 'RIG', 'PAGP', 'HP', 'CRC', 'TDW', 'CVI',
               'STNG', 'BSM', 'BTU', 'STR', 'LBRT', 'NOG', 'SDRL', 'CNX',
               'UEC', 'NS', 'WHD', 'CEIX', 'AROC', 'INSW', 'KOS', 'ARLP',
               'PARR', 'USAC', 'GPOR', 'GLNG', 'OII', 'CPE', 'CRK', 'TNK',
               'XPRO', 'DKL', 'TALO', 'CRGY', 'KNTK', 'KGS', 'HPK', 'DK',
               'DHT', 'AESI', 'MNR', 'VTLE', 'KRP', 'GLP', 'EE', 'RES', 'HLX',
               'LPG', 'WKC', 'GEL', 'NEXT', 'CLMT', 'DO', 'DMLP', 'ACDC',
               'NRP', 'NVGS', 'SBR', 'MRC', 'PUMP', 'CAPL', 'SLCA', 'NGL',
               'VTOL', 'NBR', 'GRNT', 'TK', 'LEU', 'TNP', 'DRQ', 'CLB', 'SBOW',
               'PBT', 'VTS', 'TXO', 'NR', 'BRY', 'GPRK', 'SD', 'OSG', 'REPX',
               'OIS', 'SGU', 'GFR', 'BOOM', 'SOI', 'NC', 'HNRG', 'RNGR',
               'AMPY', 'FET', 'NGS', 'EPM', 'SMLP', 'PNRG', 'GEOS', 'KLXE',
               'EP', 'MVO', 'VOC', 'BATL', 'CRT', 'AE', 'NCSM', 'CKX', 'MXC',
               'MTR'],
    'Crypto': ['BTC-USD', 'ETH-USD', 'BNB-USD', 'SOL-USD', 'XRP-USD',
               'ADA-USD', 'AVAX-USD', 'DOGE-USD', 'TRX-USD', 'LINK-USD',
               'DOT-USD', 'MATIC-USD', 'ICP-USD', 'SHIB-USD', 'DAI-USD',
               'LTC-USD', 'BCH-USD', 'UNI7083-USD', 'ATOM-USD', 'ETC-USD',
               'LEO-USD', 'OP-USD', 'TIA22861-USD', 'IMX10603-USD', 'XLM-USD',
               'INJ-USD', 'TAO22974-USD', 'NEAR-USD', 'APT21794-USD',
               'KAS-USD', 'DOKB-USD', 'FDUSD-USD', 'FIL-USD', 'LDO-USD',
               'HBAR-USD', 'XMR-USD', 'CRO-USD', 'VET-USD', 'MNT27075-USD',
               'SUI20947-USD', 'RUNE-USD', 'MKR-USD', 'RNDR-USD',
               'GRT6719-USD', 'BSV-USD', 'EGLD-USD', 'ALGO-USD', 'ORDI-USD',
               'AAVE-USD', 'QNT-USD', 'MINA-USD', 'FLOW-USD', 'HNT-USD',
               'DYM-USD', 'FTM-USD', 'SNX-USD', 'BEAM28298-USD', 'THETA-USD',
               'SAND-USD', 'BTT-USD', 'AXS-USD', 'ASTR-USD', 'XTZ-USD',
               'KCS-USD', '1000SATS-USD', 'FLR-USD', 'BGB-USD', 'CHEEL-USD',
               'CHZ-USD', 'ETHDYDX-USD', 'MANA-USD', 'CFX-USD', 'NEO-USD',
               'OSMO-USD', 'EOS-USD', 'BLUR-USD', 'ROSE-USD', 'WEMIX-USD',
               'KAVA-USD', 'IOTA-USD', 'PYTH-USD', 'BONK-USD', 'RON14101-USD',
               'KLAY-USD', 'RVN-USD', 'SUSHI-USD', 'XAI28933-USD', 'API3-USD',
               'STORJ-USD', 'BDX-USD', 'DCR-USD', 'CHR-USD', 'T-USD',
               'WAVES-USD', 'ANKR-USD', 'YFI-USD', 'LYX-USD', 'BICO-USD',
               'USTC-USD', 'MEME28301-USD', 'LCX-USD', 'Mobile', 'FNSA-USD',
               'LPT-USD', 'AUDIO-USD', 'JTO-USD', 'GAL11877-USD', 'CTSI-USD',
               'ERC20-USD', 'ICX-USD', 'OM-USD', 'OAS-USD', 'GLM-USD',
               'ONE3945-USD', 'WE20456-USD', 'ONT-USD', 'BAL-USD', 'FLUX-USD',
               'BTRST-USD', 'MOVR-USD', 'POND-USD', 'WAXP-USD', 'SXP-USD',
               'ACE28674-USD', 'TRIBE-USD', 'SFUND-USD', 'FLEX-USD', 'Lab',
               'IOST-USD', 'JOE-USD', 'LSK-USD', 'ALPH-USD', 'XVS-USD', 'Doge',
               'USDJ-USD', 'CTC-USD', 'C98-USD', 'BORG-USD', 'Forged', 'RLC',
               'ARK-USD', 'XYM-USD', 'POWR-USD'],
    'ETF': ['SPY', 'XLF', 'QQQ', 'GDX', 'XLE', 'XLU', 'XLI', 'IEF', 'VCSH',
            'SMH', 'XLV', 'SPLG', 'IEFA', 'VCIT', 'SPTI', 'XLK', 'IGSB',
            'XLRE', 'IAU', 'RSP', 'XLY', 'GLD', 'SJNK', 'USHY', 'VOO', 'XLB',
            'IJR', 'DIA', 'SCHD', 'XHB', 'SCHF', 'JPST', 'QLD', 'SPSB', 'IVV',
            'EWT', 'CALF', 'PDBC', 'SPSM', 'EMXC', 'VTV', 'BIV', 'COWZ', 'IVW',
            'SCHG', 'VGIT', 'SPYV', 'SPYG', 'EWW', 'DGRO', 'MBB', 'SCHX',
            'IJH', 'VMBS', 'EWC', 'VGSH', 'SPEM', 'IQLT', 'SPHY', 'IEI',
            'BBJP', 'SPMB', 'SOXX', 'SCHO', 'SCHP', 'XLG', 'IWF', 'SPHQ',
            'ITB', 'FBND', 'IWR', 'ANGL', 'SDVY', 'MOAT', 'ITOT', 'VIG',
            'PULS', 'SPTS', 'FNDF', 'BIZD', 'SLYV', 'FNDE', 'RDVY', 'FDL',
            'VB', 'VONG', 'CQQQ', 'VTIP', 'VO', 'CIBR', 'FLOT', 'EPI', 'VUG',
            'VPL', 'ICSH', 'OMFL', 'FPE', 'IHI', 'VNLA', 'FENY', 'SHYG',
            'SCHR', 'NEAR', 'IYE', 'FLRN', 'FALN', 'KIE', 'DGRW', 'DBC',
            'JMBS', 'QQEW', 'IUSV', 'IVE', 'VYMI', 'JCPB', 'IYW', 'SPHB',
            'IDEV', 'LMBS', 'DBEF', 'PAVE', 'VGT', 'DGS', 'GTO', 'FUTY', 'DXJ',
            'NOBL', 'VBR', 'ESGU', 'PRF', 'ICOW', 'JQUA', 'FNDX', 'DIVO',
            'PFXF', 'VFH', 'IJS', 'FLTR', 'VDE', 'DVY', 'PFFD', 'PEY', 'FTCS',
            'IWB', 'VOE', 'IUSG', 'SPTM', 'LIT', 'SDY', 'IHDG', 'SPGP', 'HEFA',
            'DIVI', 'STIP', 'XMHQ', 'FNDA', 'IAGG', 'PFFA', 'VRP', 'FDVV',
            'BBAX', 'OEF', 'IWY', 'XCEM', 'MGK', 'FTSL', 'RPV', 'EWL', 'CWB',
            'PPA', 'TIPX', 'JHMM', 'DLN', 'BLOK', 'EMLP', 'SDOG', 'SLYG',
            'JMST', 'EWD', 'FTEC', 'JVAL', 'GSY', 'ECH', 'ONEQ', 'VV', 'FPEI',
            'MGV', 'VPU', 'BSJP', 'FVAL', 'HDEF', 'VRIG', 'SLQD', 'ESGD',
            'MDYV', 'RWL', 'SMLF', 'RWJ', 'IFRA', 'EWX', 'QEFA', 'PCEF',
            'DSTL', 'JMUB', 'QQQE', 'EELV', 'PICK', 'VOOG', 'VIOO', 'IGEB',
            'LVHI', 'XSMO', 'PID', 'FHLC', 'IJJ', 'SUSA', 'LGOV', 'IMCG',
            'IXN', 'DNL', 'FSTA', 'FV', 'RLY', 'MUST', 'CZA', 'VHT', 'ICVT',
            'VOOV', 'CNYA', 'SMMD', 'FCOR', 'IOO', 'EWM', 'BAB', 'XMMO', 'ICF',
            'TDTT', 'DSI', 'FXO', 'FLIN', 'MMIT', 'IYF', 'ULST', 'NUSC',
            'FLBL', 'IUS', 'HTAB', 'FTLS', 'HYDB', 'TDTF', 'FTXL', 'FDIS',
            'IEO', 'SYLD', 'SECT', 'UITB', 'USTB', 'TMFC', 'FCOM', 'SPMO',
            'SUSB', 'EWJV', 'MLPX', 'AOA', 'FYX', 'URTH', 'EZA', 'FGD', 'HFXI',
            'REGL', 'PRFZ', 'MGC', 'FNX', 'IDHQ', 'OUSM', 'XSVM', 'PHO',
            'FSMB', 'DWAS', 'SMMU', 'HAWX', 'VIOV', 'GXG', 'CDC', 'AIRR',
            'COM', 'IGRO', 'EQWL', 'VAW', 'HEDJ', 'FIW', 'XAR', 'XSD', 'CMBS',
            'FLQM', 'HMOP', 'HYGH', 'PTNQ', 'DIVB', 'FTXN', 'PSI', 'VCR',
            'TUR', 'DBJP', 'ILCG', 'HYEM', 'FLLV', 'RDIV', 'NULG', 'PJUL',
            'KBA', 'EYLD', 'TPYP', 'ATMP', 'IVOO', 'MMIN', 'HEWJ', 'KARS',
            'QGRO', 'CHIQ', 'IETC', 'HEZU', 'DRSK', 'GSSC', 'IYK', 'NANR',
            'VONE', 'YLD', 'IDOG', 'IGBH', 'FYT', 'EES', 'JPSE', 'CWS', 'EMHY',
            'RAVI', 'RIGS', 'DTD', 'IAK', 'FLMI', 'HSRT', 'DDWM', 'JPEM',
            'IPAC', 'IGM', 'FXZ', 'CEFS', 'FIVG', 'FUMB', 'FYLD', 'HEEM',
            'FDHY', 'NUDM', 'FNDB', 'FEMS', 'PTF', 'NACP', 'CDL', 'LQDH',
            'PBTP', 'IMCV', 'IWL', 'REZ', 'DBEU', 'POCT', 'VFVA', 'FXG', 'IYH',
            'FLJH', 'PKW', 'NUMG', 'ISCF', 'PXF', 'VFMO', 'FDM', 'QTUM',
            'INDS', 'ENFR', 'EQAL', 'CEMB', 'RWK', 'DXJS', 'DALI', 'ISMD',
            'WTV', 'KBWP', 'QMOM', 'PSCC', 'JPIB', 'AGZ', 'BJUL', 'CSM', 'CSB',
            'FXL', 'EEMS', 'BLCN', 'PXE', 'EZM', 'BLES', 'BCD', 'RFV', 'IPKW',
            'SKOR', 'OMFS', 'ETHO', 'FLLA', 'PTH', 'IVOV', 'THD', 'FCTR',
            'IAI', 'IYG', 'BJAN', 'FDRR', 'KORP', 'IYM', 'TRTY', 'KURE',
            'HTUS', 'FILL', 'QWLD', 'ONEY', 'GOAU', 'IQDY', 'RAAX', 'KGRN',
            'XMVM', 'HSCZ', 'HYZD', 'PSC', 'SDG', 'RNSC', 'IHF', 'VFQY',
            'FLTW', 'CNRG', 'VSDA', 'PBUS', 'PSCI', 'CCOR', 'SHYL', 'SLX',
            'PRN', 'PSCT', 'PZT', 'KCE', 'VFMF', 'LGLV', 'LEAD', 'BOUT', 'PSR',
            'MFDX', 'EQL', 'WOMN', 'PEXL', 'VPC', 'IQIN', 'RZV', 'MFEM',
            'JPME', 'IDX', 'LQDI', 'NFTY', 'TLTD', 'BOCT', 'SPXN', 'EMTL',
            'ONEV', 'FFIU', 'LSST', 'ESGS', 'FTSD', 'EUDG', 'VLU', 'FCAL',
            'QARP', 'GDMA', 'DBAW', 'QDIV', 'EPU', 'MFUS', 'UTRN', 'NURE',
            'OPER', 'ESG', 'HYHG', 'XTL', 'JPUS', 'EDOG', 'BFIT', 'GAA',
            'USAI', 'UTES', 'YPS', 'RTH', 'SPXE', 'CBON', 'GRNB', 'SQLV',
            'DGT'],
    'Ai': ['ISRG', 'ROK', 'TER', 'PATH', 'CGNX', 'SYNA', 'SYM', 'AVAV', 'AI',
           'AMBA', 'HOLI', 'EXAI', 'SOUN', 'IRBT', 'BBAI', 'REKR', 'VRSSF',
           'MYO', 'RBOT', 'RWLK', 'AIRE', 'OSS', 'KSCP', 'NMTC', 'EKSO',
           'GFAI', 'AITX', 'SPOFF', 'MBOT', 'KITT', 'NEXCF', 'QGSI', 'TREIF',
           'AICOF', 'PKKFF', 'FOBIF', 'TMDIF', 'AIMLF', 'DTMXF', 'OTRK',
           'ATIXF', 'WINKF', 'HAPBF', 'UCLE', 'CYN', 'QCOM', 'NVDA', 'CRWD',
           'ANET', 'MSFT', 'CRM', 'ZBRA', 'INTC', 'TSM', 'GOOG', 'EQIX',
           'INTC', 'TSM', 'ANSS', 'WDC', 'AME', 'MCHP', 'TTD', 'SNOW'],
    'Robotics': ['EMR', 'ROK', 'DE', 'ZBRA', 'SYK', 'SPLK', 'TER', 'TMO',
                 'TSLA', 'PATH', 'AME', 'KITT', 'HLX', 'AMBA'],
    'Space': ['TDY', 'SIRI', 'LHX', 'SPCE', 'NOC', 'SANM', 'VSAT', 'HON',
              'CACI', 'GRMN', 'HEI', 'HEI-A', 'LMT', 'DISH', 'TRMB', 'RTX',
              'SATS'],
    'Car': ['TSLA', 'STLA', 'F', 'GM', 'RIVN', 'VFS', 'LVWR', 'NWTN', 'BLBD',
            'MULN', 'REVG', 'XPEV', 'TM', 'NIO', 'FSR'],
    'Crypto stocks': ['NVDA', 'SQ', 'PYPL', 'COIN', 'RIOT', 'BYON', 'MARA',
                      'SICP', 'MSTR'],
    'Airlines': ['DAL', 'AAL', 'ALGT', 'UAL', 'SNCY', 'RYAAY'],
    'Biotech': ['NVO', 'VRTX', 'REGN', 'MRNA', 'ARGX', 'BNTX', 'ALNY', 'GMAB',
                'RPRX', 'BMRN', 'BGNE', 'INCY', 'SRPT', 'LEGN', 'TECH', 'UTHR',
                'IMGN', 'ROIV', 'APLS', 'PCVX', 'ASND', 'CYTK', 'JAZZ', 'IONS',
                'EXEL', 'BBIO', 'NUVL', 'IMVT', 'RVMD', 'HALO', 'BPMC', 'ACAD',
                'INSM', 'ARWR', 'BHVN', 'RARE', 'MDGL', 'IMCR', 'SWTX', 'ACLX',
                'IDYA', 'KRYS', 'CBAY', 'FTRE', 'NMRA', 'ARVN', 'MOR', 'CGON',
                'CRNX', 'GLPG', 'DNLI', 'BEAM', 'RXRX', 'PTCT', 'DYN', 'SNDX',
                'EWTX', 'AMAM', 'PRTA', 'KURA', 'PHVS', 'ABCL', 'KNSA', 'RCUS',
                'AGIO', 'MRVI', 'DAWN', 'SANA', 'VIR', 'FDMT', 'BCRX', 'SRRK',
                'AUTL', 'AKRO', 'AMLX', 'MGNX', 'CABA', 'TARS', 'PLRX', 'INVA',
                'GRCL', 'VERV', 'TYRA', 'TRML', 'CRGX', 'CNTA', 'SYRE', 'OLMA',
                'ORIC', 'IGMS', 'EXAI', 'FUSN', 'CGEM', 'ZYME', 'SLRN', 'ICVX',
                'HLVX', 'RGNX', 'ALXO', 'ELVN'],
    'Canbis': ['CURLF', 'GTBIF', 'VRNOF', 'TCNNF', 'CRLBF', 'GLASF', 'CBSTF',
               'MAPS'], 'Test': ['MINA-USD']}

def count_tickers(tickers_dict):
    total_tickers = 0
    for sector, ticker_list in tickers_dict.items():
        count = len(ticker_list)
        total_tickers += count
        print(f"{sector}: {count} tickers")
    print(f"Total tickers across all sectors: {total_tickers}")


if __name__ == '__main__':
    count_tickers(all_tickers)
