tickers_basic_materials = ['LIN', 'SHW', 'SCCO', 'ECL', 'FCX', 'CRH', 'APD',
                           'NUE', 'DOW', 'NEM', 'CTVA', 'PPG', 'MLM', 'VMC',
                           'LYB', 'DD', 'IFF', 'STLD', 'WLK', 'RS', 'CE',
                           'AVTR', 'CF', 'RPM', 'ALB', 'X', 'CLF', 'MOS',
                           'EMN', 'EXP', 'SSD', 'UFPI', 'RGLD', 'AU', 'AXTA',
                           'SUM', 'FMC', 'CMC', 'OLN', 'NEU', 'BCC', 'ESI',
                           'AMR', 'AA', 'BCPC', 'ASH', 'CC', 'CBT', 'HUN',
                           'FUL', 'KNF', 'WDFC', 'KWR', 'AVNT', 'SMG', 'ARCH',
                           'HCC', 'MP', 'IOSP', 'CSTM', 'MTRN', 'SXT', 'TGLS',
                           'MTX', 'TROX', 'SCL', 'SLVM', 'NGVT', 'GPRE', 'WS',
                           'USLM', 'OEC', 'HWKN', 'ECVT', 'KOP', 'KALU', 'KRO',
                           'IE', 'GSM', 'CENX', 'LVRO', 'SXC', 'TMST', 'NEXA',
                           'WTTR', 'CMP', 'BIOX', 'SA', 'METC', 'PRM', 'WLKP',
                           'ZEUS', 'REX', 'UAN', 'ASIX', 'RDUS', 'HDSN',
                           'MATV', 'MTAL', 'LWLG', 'LXU', 'CLW', 'MERC', 'ODC',
                           'GATO', 'LZM', 'VHI', 'MUX', 'AVD', 'PLL', 'FF',
                           'IPI', 'MSB', 'SMID', 'CAPT', 'ATLX', 'TSE', 'CMCL',
                           'USAP', 'CTGO', 'CMT', 'NTIC', 'FRD', 'ACNT', 'IDR',
                           'USGO', 'JCTCF']
