tickers_biotech = ['NVO', 'VRTX', 'REGN', 'MRNA', 'ARGX', 'BNTX', 'ALNY',
                   'GMAB', 'RPRX', 'BMRN', 'BGNE', 'INCY', 'SRPT', 'LEGN',
                   'TECH', 'UTHR', 'IMGN', 'ROIV', 'APLS', 'PCVX', 'ASND',
                   'CYTK', 'JAZZ', 'IONS', 'EXEL', 'BBIO', 'NUVL', 'IMVT',
                   'RVMD', 'HALO', 'BPMC', 'ACAD', 'INSM', 'ARWR', 'BHVN',
                   'RARE', 'MDGL', 'IMCR', 'SWTX', 'ACLX', 'IDYA', 'KRYS',
                   'CBAY', 'FTRE', 'NMRA', 'ARVN', 'MOR', 'CGON', 'CRNX',
                   'GLPG', 'DNLI', 'BEAM', 'RXRX', 'PTCT', 'DYN', 'SNDX',
                   'EWTX', 'AMAM', 'PRTA', 'KURA', 'PHVS', 'ABCL', 'KNSA',
                   'RCUS', 'AGIO', 'MRVI', 'DAWN', 'SANA', 'VIR', 'FDMT',
                   'BCRX', 'SRRK', 'AUTL', 'AKRO', 'AMLX', 'MGNX', 'CABA',
                   'TARS', 'PLRX', 'INVA', 'GRCL', 'VERV', 'TYRA', 'TRML',
                   'CRGX', 'CNTA', 'SYRE', 'OLMA', 'ORIC', 'IGMS', 'EXAI',
                   'FUSN', 'CGEM', 'ZYME', 'SLRN', 'ICVX', 'HLVX', 'RGNX',
                   'ALXO', 'ELVN']
