tickers_communication_services = ['GOOG', 'META', 'NFLX', 'DIS', 'TMUS',
                                  'CMCSA', 'VZ', 'T', 'DASH', 'SPOT', 'CHTR',
                                  'EA', 'RBLX', 'TTWO', 'PINS', 'WBD', 'LYV',
                                  'WMG', 'SNAP', 'OMC', 'FWONA', 'NWSA',
                                  'FOXA', 'ROKU', 'TWLO', 'ZG', 'IPG', 'LSXMA',
                                  'MTCH', 'LBRDA', 'PARA', 'LBTYA', 'EDR',
                                  'NYT', 'TKO', 'FYBR', 'NXST', 'MSGS', 'IAC',
                                  'IRDM', 'CCOI', 'USM', 'MANU', 'LLYVA',
                                  'YELP', 'ZD', 'TGNA', 'TIGO', 'CABO', 'PLTK',
                                  'BATRA', 'IAS', 'PLAY', 'CMPR', 'LGF-B',
                                  'TDS', 'ROVR', 'WLY', 'CNK', 'STGW', 'SSTK',
                                  'GENI', 'SPHR', 'LILA', 'MGNI', 'GOGO',
                                  'SEAT', 'NRDS', 'SCHL', 'FVRR', 'SHEN',
                                  'TTGT', 'MAX', 'SBGI', 'IDT', 'DLX', 'QNST',
                                  'GTN-A', 'IMAX', 'THRY', 'AMCX', 'GRPN',
                                  'ATEX', 'ATNI', 'EVER', 'SSP', 'BOC', 'MCS',
                                  'RSVR', 'EEX', 'OOMA', 'CDLX', 'DRCT', 'TSQ',
                                  'CXDO', 'RDCM', 'SGA', 'SKLZ', 'TZOO', 'HAO']
