tickers_consumer_defensive = ['WMT', 'PG', 'COST', 'KO', 'PEP', 'PM', 'MDLZ',
                              'MO', 'CL', 'TGT', 'MNST', 'EL', 'STZ', 'KHC',
                              'KDP', 'KMB', 'HSY', 'SYY', 'KVUE', 'GIS', 'KR',
                              'DLTR', 'DG', 'ADM', 'BF-B', 'CHD', 'CLX', 'TSN',
                              'K', 'MKC', 'HRL', 'LW', 'SJM', 'CELH', 'CAG',
                              'TAP', 'BG', 'CPB', 'ACI', 'USFD', 'PFGC',
                              'COTY', 'ELF', 'BJ', 'COKE', 'BRBR', 'INGR',
                              'DAR', 'PPC', 'POST', 'SFM', 'LANC', 'IPAR',
                              'OLLI', 'FLO', 'FIZZ', 'SAM', 'FRPT', 'LOPE',
                              'SMPL', 'GHC', 'NOMD', 'JJSF', 'NWL', 'HELE',
                              'COUR', 'CALM', 'LRN', 'SPB', 'GO', 'PSMT',
                              'STRA', 'THS', 'DNUT', 'SOVO', 'UDMY', 'HIMS',
                              'LAUR', 'CENT', 'EPC', 'ATGE', 'AFYA', 'MGPI',
                              'ANDE', 'WMK', 'VGR', 'UTZ', 'IMKTA', 'CHEF',
                              'TR', 'UVV', 'HLF', 'PRDO', 'JBSS', 'COCO',
                              'FDP', 'KLG', 'AGRO', 'DOLE', 'NAPA']
