tickers_consumer_cyclical = ['AMZN', 'TSLA', 'HD', 'MCD', 'NKE', 'BKNG', 'LOW',
                             'TJX', 'SBUX', 'ABNB', 'MELI', 'STLA', 'MAR',
                             'CMG', 'ORLY', 'LULU', 'F', 'ROST', 'HLT', 'DHI',
                             'AZO', 'GM', 'LEN', 'LVS', 'YUM', 'RCL', 'CPNG',
                             'TSCO', 'ULTA', 'NVR', 'APTV', 'MBLY', 'EBAY',
                             'PHM', 'DECK', 'ROL', 'DKNG', 'GPC', 'DRI', 'CCL',
                             'BALL', 'EXPE', 'AVY', 'YUMC', 'BBY', 'RIVN',
                             'MGM', 'PKG', 'DPZ', 'WSM', 'H', 'DKS', 'AMCR',
                             'LKQ', 'BURL', 'VFS', 'IP', 'WYNN', 'KMX', 'FND',
                             'RL', 'WRK', 'CASY', 'TOL', 'FIVE', 'PAG', 'BBWI',
                             'SCI', 'TPR', 'CZR', 'CVNA', 'ONON', 'ETSY',
                             'CHDN', 'ALV', 'SKX', 'CCK', 'TXRH', 'BIRK',
                             'TPX', 'WING', 'MTN', 'LAD', 'GNTX', 'MUSA',
                             'LNW', 'LEA', 'PVH', 'GPK', 'CHWY', 'BWA', 'CART',
                             'GPS', 'AS', 'SN', 'LEVI', 'HAS', 'MHK', 'NCLH',
                             'GLBE', 'BERY', 'MAT', 'DDS', 'WH', 'HRB', 'BYD',
                             'CROX', 'AN', 'MMYT', 'THO', 'W', 'PLNT', 'CHH',
                             'CAVA', 'WHR', 'REYN', 'VFC', 'BC', 'IBP', 'BFAM',
                             'TMHC', 'MTH', 'SON', 'ANF', 'ALSN', 'CPRI',
                             'IGT', 'M', 'SEE', 'PII', 'HOG', 'ASO', 'BROS',
                             'COLM', 'SLGN', 'RH', 'SKY', 'MDC', 'KBH', 'HGV',
                             'SIG', 'GME', 'ABG', 'AEO', 'GOLF', 'WEN', 'YETI',
                             'URBN', 'MOD', 'GT', 'GPI', 'AAP', 'RUSHA', 'QS',
                             'PENN', 'UAA', 'KTB', 'RRR', 'TPH', 'MHO', 'SHAK',
                             'VC', 'SVV', 'SEAS', 'ZGN', 'SHOO', 'ADNT', 'JWN',
                             'DFH', 'CVCO', 'VAC', 'TRIP', 'CRI', 'KSS', 'TNL',
                             'GEF', 'LCII', 'LGIH', 'MCW', 'AIN', 'CCS',
                             'FOXF', 'FL', 'LEG', 'CARG', 'BOOT', 'LTH',
                             'FTDR', 'DORM', 'PTVE', 'MODG', 'ARCO', 'PATK',
                             'GRBK', 'OI', 'PZZA', 'BLMN', 'ACVA', 'VSCO',
                             'BOWL', 'DRVN', 'LVWR', 'FUN', 'SIX', 'GTX',
                             'ODP', 'BKE', 'MLKN', 'WGO', 'DAN', 'EAT', 'SAH',
                             'NWTN', 'MBC', 'CAKE', 'MSGE', 'CBRL', 'VSTO',
                             'ARHS', 'LZB', 'THRM', 'EYE', 'KAR', 'OXM',
                             'JACK', 'AMWD', 'CNNE', 'XPEL', 'OSW', 'GIII',
                             'LESL', 'PHIN', 'FWRG', 'SBH', 'SG', 'MCRI',
                             'WINA', 'RSI', 'GES', 'CARS', 'CAL', 'RVLV',
                             'PLYA', 'KRUS', 'CWH', 'GDEN', 'BYON', 'SHCO',
                             'FIGS', 'TRS', 'HOV', 'MBUU', 'BLBD', 'MNRO',
                             'AXL', 'ARKO', 'NGMS', 'EVRI', 'BZH', 'SMP',
                             'ACEL', 'HIBB', 'BJRI', 'PTLO', 'ETD', 'SCVL',
                             'HZO', 'MYE', 'DIN', 'WWW', 'SDA', 'MOV', 'LEGH',
                             'CHUY', 'FLWS', 'MED', 'PLOW', 'HVT', 'DESP',
                             'DENN', 'DBI', 'KRT', 'RICK', 'XPOF', 'BALY',
                             'TAST', 'SRI', 'LIND', 'MLR', 'BWMX', 'BH',
                             'LQDT', 'JOUT', 'JL', 'ONEW', 'CRMT', 'FNKO',
                             'LOVE', 'IRBT', 'MPX', 'MCFT', 'CSV', 'PBPB',
                             'ZUMZ', 'UHG', 'AGS', 'CYD', 'GAMB', 'GCO',
                             'JAKK', 'BBW', 'WEYS', 'CPS', 'LOCO', 'TTSH',
                             'LE', 'NATH', 'JILL', 'HOFT', 'HBB', 'GENK',
                             'CTRN', 'KFS', 'INSE', 'VRA', 'ESCA', 'CLAR',
                             'RMBL', 'SGC', 'SNBR', 'TLYS', 'CVGI', 'RCKY',
                             'LCUT', 'FLL', 'FLXS', 'MPAA', 'RRGB', 'PLCE',
                             'VIRC', 'FAT', 'CATO', 'BSET', 'LAKE', 'BGFV',
                             'AOUT', 'CPHC', 'STRT', 'UFI', 'AKA', 'KEQU',
                             'LIVE', 'NHTC', 'CULP', 'REE', 'CRWS', 'DLA',
                             'ARKR', 'INTG', 'BDL', 'MULN', 'CREV', 'RGS',
                             'YOSH', 'PMNT']
