tickers_energy = ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'PSX', 'MPC', 'EPD',
                  'PXD', 'OXY', 'VLO', 'ET', 'HES', 'WMB', 'OKE', 'MPLX',
                  'LNG', 'KMI', 'HAL', 'BKR', 'FANG', 'DVN', 'CQP', 'TRGP',
                  'CTRA', 'EQT', 'MRO', 'DINO', 'OVV', 'TPL', 'PAA', 'WES',
                  'PR', 'CHK', 'APA', 'FTI', 'HESM', 'IEP', 'SWN', 'WFRD',
                  'NOV', 'RRC', 'PBF', 'MTDR', 'CHRD', 'AR', 'NE', 'CIVI',
                  'MUR', 'AM', 'VNOM', 'CHX', 'ENLC', 'VVV', 'SUN', 'DTM',
                  'FRO', 'VAL', 'ETRN', 'NFG', 'PTEN', 'SM', 'MGY', 'RIG',
                  'PAGP', 'HP', 'CRC', 'TDW', 'CVI', 'STNG', 'BSM', 'BTU',
                  'STR', 'LBRT', 'NOG', 'SDRL', 'CNX', 'UEC', 'NS', 'WHD',
                  'CEIX', 'AROC', 'INSW', 'KOS', 'ARLP', 'PARR', 'USAC',
                  'GPOR', 'GLNG', 'OII', 'CPE', 'CRK', 'TNK', 'XPRO', 'DKL',
                  'TALO', 'CRGY', 'KNTK', 'KGS', 'HPK', 'DK', 'DHT', 'AESI',
                  'MNR', 'VTLE', 'KRP', 'GLP', 'EE', 'RES', 'HLX', 'LPG',
                  'WKC', 'GEL', 'NEXT', 'CLMT', 'DO', 'DMLP', 'ACDC', 'NRP',
                  'NVGS', 'SBR', 'MRC', 'PUMP', 'CAPL', 'SLCA', 'NGL', 'VTOL',
                  'NBR', 'GRNT', 'TK', 'LEU', 'TNP', 'DRQ', 'CLB', 'SBOW',
                  'PBT', 'VTS', 'TXO', 'NR', 'BRY', 'GPRK', 'SD', 'OSG',
                  'REPX', 'OIS', 'SGU', 'GFR', 'BOOM', 'SOI', 'NC', 'HNRG',
                  'RNGR', 'AMPY', 'FET', 'NGS', 'EPM', 'SMLP', 'PNRG', 'GEOS',
                  'KLXE', 'EP', 'MVO', 'VOC', 'BATL', 'CRT', 'AE', 'NCSM',
                  'CKX', 'MXC', 'MTR']
