tickers_financial_services = ['BRK-B', 'JPM', 'V', 'MA', 'BAC', 'WFC', 'BX',
                              'AXP', 'MS', 'SPGI', 'RY', 'C', 'GS', 'BLK',
                              'SCHW', 'TD', 'PGR', 'CB', 'MMC', 'KKR', 'ICE',
                              'MCO', 'CME', 'PYPL', 'USB', 'APO', 'AON', 'PNC',
                              'AJG', 'COF', 'MET', 'TRV', 'AIG', 'TFC', 'NU',
                              'MSCI', 'AFL', 'ARES', 'BK', 'ALL', 'IBKR',
                              'AMP', 'PRU', 'COIN', 'NDAQ', 'ACGL', 'WTW',
                              'DFS', 'HIG', 'OWL', 'TW', 'RJF', 'TROW', 'BRO',
                              'RKT', 'FITB', 'MTB', 'STT', 'UWMC', 'FCNCA',
                              'WRB', 'CBOE', 'MKL', 'PFG', 'ERIE', 'LPLA',
                              'FDS', 'HBAN', 'CINF', 'RF', 'NTRS', 'CG', 'L',
                              'TPG', 'SYF', 'EG', 'ALLY', 'CRBG', 'CFG', 'BEN',
                              'FNF', 'XP', 'KEY', 'CNA', 'BAP', 'MORN', 'RNR',
                              'GL', 'ARCC', 'RYAN', 'EQH', 'RGA', 'AFG',
                              'HOOD', 'EWBC', 'KNSL', 'UNM', 'AIZ', 'HLI',
                              'SEIC', 'JEF', 'PRI', 'MKTX', 'WBS', 'SOFI',
                              'ORI', 'SF', 'FHN', 'VOYA', 'IVZ', 'CACC', 'CMA',
                              'WAL', 'EVR', 'CBSH', 'CFR', 'RLI', 'HLNE',
                              'PNFP', 'SSB', 'BPOP', 'FAF', 'SIGI', 'ZION',
                              'PB', 'FG', 'WTFC', 'OBDC', 'FSK', 'ESNT',
                              'BOKF', 'OMF', 'FCFS', 'MARA', 'SNV', 'AMG',
                              'PDI', 'BXSL', 'MTG', 'AXS', 'JHG', 'FRHC',
                              'CADE', 'DNB', 'OZK', 'HOMB', 'UBSI', 'ONB',
                              'THG', 'FNB', 'AGO', 'COOP', 'PFSI', 'FFIN',
                              'ESGR', 'AEL', 'WU', 'LNC', 'ACT', 'SLM', 'VLY',
                              'RDN', 'CRVL', 'WTM', 'GBCI', 'JXN', 'STEP',
                              'UMBF', 'COLB', 'KMPR', 'PJT', 'BGC', 'PSLV',
                              'MAIN', 'TFSL', 'HWC', 'AB', 'MC', 'CNS', 'SFBS',
                              'LAZ', 'BHF', 'NNI', 'IBOC', 'ABCB', 'NEA',
                              'UCBI', 'GSHD', 'BUR', 'WD', 'DNP', 'ASB', 'FHI',
                              'RIOT', 'CNO', 'APAM', 'BANF', 'AX', 'CATY',
                              'UPST', 'FBP', 'PIPR', 'HGTY', 'TCBI', 'GNW',
                              'CLSK', 'FHB', 'FIBK', 'VIRT', 'NAD', 'GBDC',
                              'HTGC', 'WSFS', 'FULT', 'NVG', 'CSQ', 'AUB',
                              'EBC', 'BOH', 'NMIH', 'EXG', 'VCTR', 'INTR',
                              'CVBF', 'CBU', 'AMK', 'PPBI', 'TBBK', 'ADX',
                              'NZF', 'SFNC', 'INDB', 'MCY', 'BANC', 'PSEC',
                              'PAX', 'PRK', 'FFBC', 'UTF', 'SBCF', 'SNEX',
                              'TOWN', 'SPNT', 'ETY', 'HTH', 'FRME', 'PTY',
                              'GDV', 'BKU', 'UTG', 'DFIN', 'TSLX', 'IBTX',
                              'TFIN', 'BIGZ', 'NAVI', 'NUV', 'WAFD', 'CLBK',
                              'MSDL', 'GOF', 'USA', 'RNST', 'OBDE', 'NWLI',
                              'MBIN', 'DWAC', 'BFH', 'ECAT', 'BMEZ', 'LOB',
                              'FBK', 'OFG', 'AGM-A', 'WSBC', 'BCAT', 'VRTS',
                              'LKFN', 'TRMK', 'EVT', 'STC', 'GCMG', 'CLM',
                              'GSBD', 'CUBI', 'RVT', 'ENVA', 'NBTB', 'NAC',
                              'RQI', 'GAB', 'BRP', 'OCSL', 'FIHL', 'BANR',
                              'HMN', 'NWBI', 'CHCO', 'PLMR', 'ETV', 'BTT',
                              'EFSC', 'BDJ', 'FBNC', 'KYN', 'PDO', 'HTLF',
                              'BSTZ', 'NTB', 'STEW', 'HYT', 'SYBT', 'BXMX',
                              'FCF', 'ETG', 'CASH', 'DSL', 'NBHC', 'STEL',
                              'HOPE', 'BUSE', 'NMFC', 'TRUP', 'BST', 'SAFT',
                              'SRCE', 'SKWD', 'STBA', 'WABC', 'ECPG', 'PFS',
                              'OXLC', 'NFJ', 'LMND', 'QQQX', 'TCBK', 'EVV',
                              'BRDG', 'NIC', 'JFR', 'NMZ', 'PWP', 'VBTX',
                              'CET', 'EIG', 'PX', 'WT', 'GAM', 'MUC', 'FPF',
                              'EOS', 'PTA', 'BBN', 'SASR', 'BTZ', 'CSWC',
                              'PEBO', 'SCRM', 'BHLB', 'CVII', 'NCDL', 'BCSF',
                              'QCRH', 'RBCAA', 'RNP', 'GABC', 'OCFC', 'AMSF',
                              'LC', 'PFBC', 'NRK', 'PRAA', 'BBDC', 'OBK',
                              'SBSI', 'HCI', 'BY', 'CHY', 'BRKL', 'GHLD',
                              'LPRO', 'MFIC', 'AWF', 'BSIG', 'BFC', 'MQY',
                              'ETW', 'BLX', 'CII', 'AOD', 'MUI', 'HQH', 'HG',
                              'CHI', 'CFFN', 'SLRC', 'LBAI', 'CNOB', 'THQ',
                              'CRF']

