tickers_healthcare = ['LLY', 'UNH', 'JNJ', 'MRK', 'ABBV', 'TMO', 'ABT', 'DHR',
                      'AMGN', 'PFE', 'ISRG', 'SYK', 'ELV', 'MDT', 'VRTX',
                      'REGN', 'BMY', 'CVS', 'CI', 'BSX', 'GILD', 'ZTS', 'HCA',
                      'BDX', 'MCK', 'EW', 'IDXX', 'COR', 'DXCM', 'HUM', 'CNC',
                      'IQV', 'A', 'GEHC', 'BIIB', 'VEEV', 'MRNA', 'WST', 'RMD',
                      'ZBH', 'CAH', 'MTD', 'ICLR', 'ALGN', 'MOH', 'STE',
                      'ILMN', 'ALNY', 'BAX', 'WBA', 'WAT', 'LH', 'COO', 'RPRX',
                      'HOLX', 'BMRN', 'DGX', 'VTRS', 'PODD', 'NBIX', 'INCY',
                      'RVTY', 'KRTX', 'SRPT', 'TFX', 'EXAS', 'RGEN', 'CRL',
                      'UHS', 'TECH', 'PEN', 'CTLT', 'DVA', 'MEDP', 'UTHR',
                      'QGEN', 'BRKR', 'HSIC', 'BIO', 'ATR', 'THC', 'CHE',
                      'IMGN', 'ROIV', 'STVN', 'SWAV', 'NTRA', 'APLS', 'PCVX',
                      'ELAN', 'CYTK', 'CERE', 'JAZZ', 'ACHC', 'IONS', 'EHC',
                      'GMED', 'MASI', 'XRAY', 'ITCI', 'HQY', 'ENSG', 'EXEL',
                      'BBIO', 'TXG', 'OPCH', 'INSP', 'CRSP', 'DOCS', 'NUVL',
                      'IMVT', 'RVMD', 'GKOS', 'HALO', 'BPMC', 'MMSI', 'ALKS',
                      'SHC', 'AXSM', 'QDEL', 'RCM', 'ACAD', 'PRGO', 'SGRY',
                      'OGN', 'ALVO', 'INSM', 'ARWR', 'OSCR', 'FOLD', 'BHVN',
                      'PGNY', 'LNTH', 'RARE', 'MLTX', 'XENE', 'HAE', 'NVST',
                      'MDGL', 'RYZB', 'IRTC', 'AZTA', 'NEOG', 'EVH', 'ITGR',
                      'AXNX', 'TDOC', 'PBH', 'NARI', 'SEM', 'SWTX', 'ACLX',
                      'IART', 'IDYA', 'KRYS', 'VKTX', 'AMED', 'RYTM', 'CBAY',
                      'TMDX', 'AMN', 'FTRE', 'NMRA', 'AGL', 'CERT', 'ARVN',
                      'GH', 'LIVN', 'CNMD', 'AMPH', 'RCKT', 'PDCO', 'GDRX',
                      'CGON', 'CRNX', 'RDNT', 'PINC', 'NTLA', 'PRCT', 'LFST',
                      'DNLI', 'PRVA', 'ICUI', 'IRWD', 'CORT', 'BEAM', 'MRUS',
                      'IOVA', 'VERA', 'ATEC', 'ARDX', 'VCEL', 'TGTX', 'KYMR',
                      'TWST', 'RXRX', 'INMD', 'CLDX', 'MYGN', 'SDGR', 'MORF',
                      'HRMY', 'BTSG', 'PTCT', 'DYN', 'SNDX', 'VCYT', 'NEO',
                      'KROS', 'APGE', 'EWTX', 'RXST', 'PACB', 'INBX', 'AMAM',
                      'AMRX', 'AMEH', 'ALPN', 'NAMS', 'DVAX', 'IRON', 'NVCR',
                      'WRBY', 'OMI', 'CPRX', 'TARO', 'ATRC', 'PHR', 'PTGX',
                      'ADUS', 'SUPN', 'PRTA', 'TNDM', 'KURA', 'SLNO', 'PHVS',
                      'ABCL', 'STAA', 'USPH', 'KNSA', 'RCUS', 'SAGE', 'NHC',
                      'EYPT', 'AGIO', 'MRVI', 'LMAT', 'DAWN', 'PCRX', 'UFPT',
                      'LGND', 'MIRM', 'SANA', 'ALHC', 'DCPH', 'TNGX', 'VIR',
                      'OMCL', 'FDMT', 'BCRX', 'FNA', 'AUPH', 'ADMA', 'XNCR',
                      'IMTX', 'MDXG', 'RLAY', 'ANIP', 'LQDA', 'CTKB', 'SRRK',
                      'VRDN', 'AKRO', 'COLL', 'AMLX', 'DH', 'MGNX', 'CABA',
                      'RNA', 'ARCT', 'SAVA', 'ACCD', 'IMNM', 'ESTA', 'BKD',
                      'TARS', 'GYRE', 'PLRX', 'AHCO', 'INVA', 'VERV', 'AGTI',
                      'TYRA', 'TMCI', 'NRC', 'TRML', 'EMBC', 'MDRX', 'CRGX',
                      'QTRX']
