tickers_real_estate = ['EXPI', 'PEB', 'GNL', 'AKR', 'IVT', 'AAT', 'ROIC',
                       'JBGS', 'FOR', 'NXRT', 'RC', 'VRE', 'ARI', 'MMI',
                       'SAFE', 'XHR', 'GTY', 'NTST', 'CMTG', 'KW', 'LADR',
                       'SVC', 'TWO', 'LTC', 'ELME', 'ALEX', 'BFS', 'PMT',
                       'ALX', 'DEA', 'HPP', 'MFA', 'AIV', 'AHH', 'PLYM',
                       'FBRT', 'UMH', 'EFC', 'ARR', 'RDFN', 'CSR', 'BRSP',
                       'RWT', 'HOUS', 'PDM', 'CBL', 'CHCT', 'INN', 'DX',
                       'NYMT', 'KREF', 'WSR', 'GMRE', 'FRPH', 'FPI', 'PKST',
                       'UHT', 'SRG', 'CLDT', 'GOOD', 'LAND', 'ACRE', 'LSEA',
                       'OLP', 'RMR', 'ORC', 'IVR', 'STRW', 'TRTX', 'MLP',
                       'PSTL', 'CTO', 'ARL', 'NLOP', 'TCI', 'NREF', 'BRT',
                       'RMAX', 'REFI', 'GPMT', 'NXDT', 'AOMR', 'OPAD', 'PINE',
                       'AFCG', 'CLPR', 'SDHC', 'OZ', 'STRS', 'SEVN', 'MITT',
                       'STHO', 'MDV', 'AXR', 'EARN', 'ACR', 'BHM', 'NYC',
                       'GYRO', 'MDRR']
