tickers_technology = ['MSFT', 'AAPL', 'NVDA', 'AVGO', 'ORCL', 'ADBE', 'CRM',
                      'AMD', 'ACN', 'CSCO', 'INTU', 'INTC', 'IBM', 'QCOM',
                      'NOW', 'AMAT', 'TXN', 'UBER', 'LRCX', 'PANW', 'SHOP',
                      'ADI', 'MU', 'KLAC', 'ANET', 'SNPS', 'FI', 'CDNS',
                      'WDAY', 'CRWD', 'SNOW', 'APH', 'DELL', 'NXPI', 'MRVL',
                      'ROP', 'ADSK', 'TEAM', 'MSI', 'FTNT', 'PLTR', 'MCHP',
                      'TEL', 'DDOG', 'SMCI', 'SQ', 'CTSH', 'ZS', 'FIS', 'IT',
                      'NET', 'MDB', 'MPWR', 'TTD', 'ON', 'FICO', 'CDW', 'HUBS',
                      'GFS', 'ANSS', 'FTV', 'KEYS', 'HPQ', 'GLW', 'SPLK',
                      'GRMN', 'BR', 'PTC', 'TDY', 'VRSN', 'HPE', 'ZM', 'FLT',
                      'AKAM', 'CHKP', 'IOT', 'ENTG', 'STX', 'TYL', 'NTAP',
                      'WDC', 'JBL', 'SWKS', 'ENPH', 'EPAM', 'FSLR', 'GDDY',
                      'DT', 'TER', 'BSY', 'LDOS', 'APP', 'MANH', 'SSNC',
                      'PATH', 'OKTA', 'PSTG', 'NTNX', 'GEN', 'AFRM', 'TRMB',
                      'ZBRA', 'ESTC', 'U', 'JKHY', 'GTLB', 'AZPN', 'JNPR',
                      'CYBR', 'ZI', 'MNDY', 'FLEX', 'DBX', 'FFIV', 'PAYC',
                      'QRVO', 'PCOR', 'MSTR', 'DOX', 'DOCU', 'TOST', 'GLOB',
                      'CFLT', 'GWRE', 'LSCC', 'COHR', 'PCTY', 'WEX', 'INFA',
                      'SNX', 'S', 'ONTO', 'OLED', 'NXT', 'APPF', 'CIEN',
                      'DUOL', 'CACI', 'MKSI', 'KVYO', 'SPSC', 'AMKR', 'WIX',
                      'ALTR', 'FN', 'PSN', 'UI', 'DV', 'BILL', 'SAIC', 'CCCS',
                      'G', 'SMAR', 'FRSH', 'FOUR', 'CGNX', 'QLYS', 'RMBS',
                      'NSIT', 'CLVT', 'LFUS', 'TENB', 'ALGM', 'ARW', 'MTSI',
                      'NOVT', 'BRZE', 'FIVN', 'STNE', 'VRNS', 'VNT', 'CNXC',
                      'CWAN', 'WK', 'GBTG', 'ALIT', 'LYFT', 'EXLS', 'PWSC',
                      'KD', 'CRUS', 'ST', 'DLO', 'HCP', 'IPGP', 'EEFT', 'TDC',
                      'POWI', 'NVMI', 'SLAB', 'ASGN', 'SQSP', 'BLKB', 'SEDG',
                      'ASAN', 'SYNA', 'BMI', 'PAGS', 'PEGA', 'CVLT', 'FROG',
                      'ACLS', 'VERX', 'AVT', 'DXC', 'BOX', 'BL', 'RPD', 'SPT',
                      'SATS', 'CAMT', 'WOLF', 'CRDO', 'NCNO', 'INST', 'CXM',
                      'PYCR', 'ITRI', 'BDC', 'AYX', 'RUN', 'AI', 'SANM',
                      'DOCN', 'RELY', 'LITE', 'FORM', 'ACIW', 'ALRM', 'DIOD',
                      'FSLY', 'RNG', 'SRAD', 'VSH', 'MQ', 'YOU', 'PI', 'INTA',
                      'ENV', 'SITM', 'KLIC', 'SHLS', 'FLYW', 'EVTC', 'PLXS',
                      'IDCC', 'ODD', 'RAMP', 'JAMF', 'QTWO', 'ESE', 'PRFT',
                      'PRGS', 'BMBL', 'VSAT', 'ALKT', 'AVDX', 'NABL', 'AGYS',
                      'APPN', 'OSIS', 'PD', 'ARRY', 'IONQ', 'CALX', 'XRX',
                      'SONO', 'AMBA', 'ROG', 'RUM', 'VYX', 'SWI', 'ZETA',
                      'PLAB', 'PLUS', 'PAY', 'VIAV', 'VRNT', 'UCTT', 'VICR',
                      'VECO', 'EVCM', 'CLBT', 'PAYO', 'UPBD', 'CNXN', 'SEMR',
                      'PRO', 'AMPL', 'NATL', 'TTMI', 'COHU', 'EXTR', 'CSGS',
                      'SPNS', 'MXL', 'HLIT', 'AVPT', 'VZIO', 'NTCT', 'MLNK',
                      'CSIQ', 'KN', 'GRND', 'VTEX', 'NOVA', 'CTS', 'ADEA',
                      'CRSR', 'SMTC', 'PAR', 'BASE', 'PDFS', 'STER', 'ICHR',
                      'ZUO', 'DBD', 'INFN', 'INDI', 'NVTS', 'GCT', 'SGH',
                      'EVBG', 'CRCT', 'ACMR', 'TASK', 'MODN', 'BHE', 'DGII',
                      'GDYN', 'SCSC', 'ATEN', 'OLO', 'WKME', 'WEAV', 'BELFB',
                      'SSYS', 'EB', 'BTDR', 'TTEC', 'PSFE', 'WALD', 'DMRC',
                      'RDWR', 'PUBM', 'RPAY', 'AAOI', 'MEI', 'YEXT', 'ENFN',
                      'IMXI', 'KARO', 'CRNC', 'AOSL', 'BIGC', 'LASR', 'SNPO',
                      'HCKT', 'IIIV', 'SCWX', 'MITK', 'DSP', 'SMWB', 'CGNT',
                      'ITRN', 'ADTN', 'CEVA', 'ML', 'MLAB', 'AEHR', 'LAW',
                      'UIS', 'SKYT', 'XPER', 'ALNT', 'CTLP', 'DJCO', 'RDZN',
                      'CLFD', 'FARO', 'DOMO', 'VPG', 'OSPN', 'AVNW', 'NVEC',
                      'LYTS', 'NTGR', 'CCSI', 'AMSWA', 'BAND', 'GILT', 'DAKT',
                      'BLZE', 'ONTF', 'INOD', 'IBEX', 'MAXN', 'CLMB', 'LUNA',
                      'SSTI']
